### ISSUE TITLE
Shutting down this org?

### ISSUE THREAD

**Issue by konklone** [our/net#1]
I think I'd like to shut down the org. Or, failing that, I'd be happy to transfer it to someone who wanted to oversee it. But I don't think it's generally been all that successful, and it would probably make more sense to just transfer the repos out and close the org.

@dphiffer Want to transfer this repo to your personal account?

**Comment by dphiffer** [comment]
Done! Thanks for the heads up, @konklone.

**Comment by konklone** [comment]
Cool! The org has been deleted. Thanks for the quick assist.

**Comment by konklone** [comment]
(For posterity, this was originally in the `@our` organization on GitHub, under `our/net`.)
